source "https://rubygems.org"

gem "grpc", "~> 1.60"
gem "google-protobuf", "~> 3.25"
gem "toml-rb", "~> 2.2"

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.60"
  gem "grpc-tools", "~> 1.60"
end
