package com.modal.modalkt

typealias TaskRouterProto = modal.task_command_router.TaskCommandRouterOuterClass

typealias TaskExecPollRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecPollRequest
typealias TaskExecPollResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecPollResponse
typealias TaskExecStartRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStartRequest
typealias TaskExecStartResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStartResponse
typealias TaskExecStdinWriteRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdinWriteRequest
typealias TaskExecStdinWriteResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdinWriteResponse
typealias TaskExecStdioReadRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdioReadRequest
typealias TaskExecStdioReadResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdioReadResponse
typealias TaskExecWaitRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecWaitRequest
typealias TaskExecWaitResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecWaitResponse
typealias TaskExecStdoutConfig = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdoutConfig
typealias TaskExecStderrConfig = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStderrConfig
typealias TaskExecStdioFileDescriptor = modal.task_command_router.TaskCommandRouterOuterClass.TaskExecStdioFileDescriptor
typealias TaskMountDirectoryRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskMountDirectoryRequest
typealias TaskSnapshotDirectoryRequest = modal.task_command_router.TaskCommandRouterOuterClass.TaskSnapshotDirectoryRequest
typealias TaskSnapshotDirectoryResponse = modal.task_command_router.TaskCommandRouterOuterClass.TaskSnapshotDirectoryResponse
