# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: modal_proto/api.proto for package 'modal.client'

require 'grpc'
require 'modal_proto/api_pb'

module Modal
  module Client
    module ModalClient
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'modal.client.ModalClient'

        # Apps
        rpc :AppClientDisconnect, ::Modal::Client::AppClientDisconnectRequest, ::Google::Protobuf::Empty
        rpc :AppCreate, ::Modal::Client::AppCreateRequest, ::Modal::Client::AppCreateResponse
        rpc :AppDeploy, ::Modal::Client::AppDeployRequest, ::Modal::Client::AppDeployResponse
        rpc :AppDeploymentHistory, ::Modal::Client::AppDeploymentHistoryRequest, ::Modal::Client::AppDeploymentHistoryResponse
        rpc :AppGetByDeploymentName, ::Modal::Client::AppGetByDeploymentNameRequest, ::Modal::Client::AppGetByDeploymentNameResponse
        rpc :AppGetLayout, ::Modal::Client::AppGetLayoutRequest, ::Modal::Client::AppGetLayoutResponse
        rpc :AppGetLogs, ::Modal::Client::AppGetLogsRequest, stream(::Modal::Client::TaskLogsBatch)
        rpc :AppGetObjects, ::Modal::Client::AppGetObjectsRequest, ::Modal::Client::AppGetObjectsResponse
        rpc :AppGetOrCreate, ::Modal::Client::AppGetOrCreateRequest, ::Modal::Client::AppGetOrCreateResponse
        rpc :AppHeartbeat, ::Modal::Client::AppHeartbeatRequest, ::Google::Protobuf::Empty
        rpc :AppList, ::Modal::Client::AppListRequest, ::Modal::Client::AppListResponse
        rpc :AppLookup, ::Modal::Client::AppLookupRequest, ::Modal::Client::AppLookupResponse
        rpc :AppPublish, ::Modal::Client::AppPublishRequest, ::Modal::Client::AppPublishResponse
        rpc :AppRollback, ::Modal::Client::AppRollbackRequest, ::Google::Protobuf::Empty
        rpc :AppSetObjects, ::Modal::Client::AppSetObjectsRequest, ::Google::Protobuf::Empty
        rpc :AppStop, ::Modal::Client::AppStopRequest, ::Google::Protobuf::Empty
        # Input Plane
        # These RPCs are experimental, not deployed to production, and can be changed / removed
        # without needing to worry about backwards compatibility.
        rpc :AttemptAwait, ::Modal::Client::AttemptAwaitRequest, ::Modal::Client::AttemptAwaitResponse
        rpc :AttemptRetry, ::Modal::Client::AttemptRetryRequest, ::Modal::Client::AttemptRetryResponse
        rpc :AttemptStart, ::Modal::Client::AttemptStartRequest, ::Modal::Client::AttemptStartResponse
        # Blobs
        rpc :BlobCreate, ::Modal::Client::BlobCreateRequest, ::Modal::Client::BlobCreateResponse
        rpc :BlobGet, ::Modal::Client::BlobGetRequest, ::Modal::Client::BlobGetResponse
        # Classes
        rpc :ClassCreate, ::Modal::Client::ClassCreateRequest, ::Modal::Client::ClassCreateResponse
        rpc :ClassGet, ::Modal::Client::ClassGetRequest, ::Modal::Client::ClassGetResponse
        # Clients
        rpc :ClientHello, ::Google::Protobuf::Empty, ::Modal::Client::ClientHelloResponse
        # Clusters
        rpc :ClusterGet, ::Modal::Client::ClusterGetRequest, ::Modal::Client::ClusterGetResponse
        rpc :ClusterList, ::Modal::Client::ClusterListRequest, ::Modal::Client::ClusterListResponse
        # Container
        rpc :ContainerCheckpoint, ::Modal::Client::ContainerCheckpointRequest, ::Google::Protobuf::Empty
        rpc :ContainerExec, ::Modal::Client::ContainerExecRequest, ::Modal::Client::ContainerExecResponse
        rpc :ContainerExecGetOutput, ::Modal::Client::ContainerExecGetOutputRequest, stream(::Modal::Client::RuntimeOutputBatch)
        rpc :ContainerExecPutInput, ::Modal::Client::ContainerExecPutInputRequest, ::Google::Protobuf::Empty
        rpc :ContainerExecWait, ::Modal::Client::ContainerExecWaitRequest, ::Modal::Client::ContainerExecWaitResponse
        rpc :ContainerFilesystemExec, ::Modal::Client::ContainerFilesystemExecRequest, ::Modal::Client::ContainerFilesystemExecResponse
        rpc :ContainerFilesystemExecGetOutput, ::Modal::Client::ContainerFilesystemExecGetOutputRequest, stream(::Modal::Client::FilesystemRuntimeOutputBatch)
        rpc :ContainerHeartbeat, ::Modal::Client::ContainerHeartbeatRequest, ::Modal::Client::ContainerHeartbeatResponse
        rpc :ContainerHello, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :ContainerLog, ::Modal::Client::ContainerLogRequest, ::Google::Protobuf::Empty
        rpc :ContainerStop, ::Modal::Client::ContainerStopRequest, ::Modal::Client::ContainerStopResponse
        # Dicts
        rpc :DictClear, ::Modal::Client::DictClearRequest, ::Google::Protobuf::Empty
        rpc :DictContains, ::Modal::Client::DictContainsRequest, ::Modal::Client::DictContainsResponse
        rpc :DictContents, ::Modal::Client::DictContentsRequest, stream(::Modal::Client::DictEntry)
        rpc :DictDelete, ::Modal::Client::DictDeleteRequest, ::Google::Protobuf::Empty
        rpc :DictGet, ::Modal::Client::DictGetRequest, ::Modal::Client::DictGetResponse
        rpc :DictGetOrCreate, ::Modal::Client::DictGetOrCreateRequest, ::Modal::Client::DictGetOrCreateResponse
        rpc :DictHeartbeat, ::Modal::Client::DictHeartbeatRequest, ::Google::Protobuf::Empty
        rpc :DictLen, ::Modal::Client::DictLenRequest, ::Modal::Client::DictLenResponse
        rpc :DictList, ::Modal::Client::DictListRequest, ::Modal::Client::DictListResponse
        rpc :DictPop, ::Modal::Client::DictPopRequest, ::Modal::Client::DictPopResponse
        rpc :DictUpdate, ::Modal::Client::DictUpdateRequest, ::Modal::Client::DictUpdateResponse
        # Domains
        rpc :DomainCertificateVerify, ::Modal::Client::DomainCertificateVerifyRequest, ::Modal::Client::DomainCertificateVerifyResponse
        rpc :DomainCreate, ::Modal::Client::DomainCreateRequest, ::Modal::Client::DomainCreateResponse
        rpc :DomainList, ::Modal::Client::DomainListRequest, ::Modal::Client::DomainListResponse
        # Environments
        rpc :EnvironmentCreate, ::Modal::Client::EnvironmentCreateRequest, ::Google::Protobuf::Empty
        rpc :EnvironmentDelete, ::Modal::Client::EnvironmentDeleteRequest, ::Google::Protobuf::Empty
        rpc :EnvironmentGetOrCreate, ::Modal::Client::EnvironmentGetOrCreateRequest, ::Modal::Client::EnvironmentGetOrCreateResponse
        rpc :EnvironmentList, ::Google::Protobuf::Empty, ::Modal::Client::EnvironmentListResponse
        rpc :EnvironmentUpdate, ::Modal::Client::EnvironmentUpdateRequest, ::Modal::Client::EnvironmentListItem
        # Functions
        rpc :FunctionAsyncInvoke, ::Modal::Client::FunctionAsyncInvokeRequest, ::Modal::Client::FunctionAsyncInvokeResponse
        rpc :FunctionBindParams, ::Modal::Client::FunctionBindParamsRequest, ::Modal::Client::FunctionBindParamsResponse
        rpc :FunctionCallCancel, ::Modal::Client::FunctionCallCancelRequest, ::Google::Protobuf::Empty
        rpc :FunctionCallGetDataIn, ::Modal::Client::FunctionCallGetDataRequest, stream(::Modal::Client::DataChunk)
        rpc :FunctionCallGetDataOut, ::Modal::Client::FunctionCallGetDataRequest, stream(::Modal::Client::DataChunk)
        rpc :FunctionCallList, ::Modal::Client::FunctionCallListRequest, ::Modal::Client::FunctionCallListResponse
        rpc :FunctionCallPutDataOut, ::Modal::Client::FunctionCallPutDataRequest, ::Google::Protobuf::Empty
        rpc :FunctionCreate, ::Modal::Client::FunctionCreateRequest, ::Modal::Client::FunctionCreateResponse
        rpc :FunctionGet, ::Modal::Client::FunctionGetRequest, ::Modal::Client::FunctionGetResponse
        rpc :FunctionGetCallGraph, ::Modal::Client::FunctionGetCallGraphRequest, ::Modal::Client::FunctionGetCallGraphResponse
        rpc :FunctionGetCurrentStats, ::Modal::Client::FunctionGetCurrentStatsRequest, ::Modal::Client::FunctionStats
        rpc :FunctionGetDynamicConcurrency, ::Modal::Client::FunctionGetDynamicConcurrencyRequest, ::Modal::Client::FunctionGetDynamicConcurrencyResponse
        rpc :FunctionGetInputs, ::Modal::Client::FunctionGetInputsRequest, ::Modal::Client::FunctionGetInputsResponse
        # For containers to request next call
        rpc :FunctionGetOutputs, ::Modal::Client::FunctionGetOutputsRequest, ::Modal::Client::FunctionGetOutputsResponse
        # Returns the next result(s) for an entire function call (FunctionMap)
        rpc :FunctionGetSerialized, ::Modal::Client::FunctionGetSerializedRequest, ::Modal::Client::FunctionGetSerializedResponse
        rpc :FunctionMap, ::Modal::Client::FunctionMapRequest, ::Modal::Client::FunctionMapResponse
        rpc :FunctionPrecreate, ::Modal::Client::FunctionPrecreateRequest, ::Modal::Client::FunctionPrecreateResponse
        rpc :FunctionPutInputs, ::Modal::Client::FunctionPutInputsRequest, ::Modal::Client::FunctionPutInputsResponse
        rpc :FunctionPutOutputs, ::Modal::Client::FunctionPutOutputsRequest, ::Google::Protobuf::Empty
        # For containers to return result
        rpc :FunctionRetryInputs, ::Modal::Client::FunctionRetryInputsRequest, ::Modal::Client::FunctionRetryInputsResponse
        rpc :FunctionStartPtyShell, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :FunctionUpdateSchedulingParams, ::Modal::Client::FunctionUpdateSchedulingParamsRequest, ::Modal::Client::FunctionUpdateSchedulingParamsResponse
        # Images
        rpc :ImageFromId, ::Modal::Client::ImageFromIdRequest, ::Modal::Client::ImageFromIdResponse
        rpc :ImageGetOrCreate, ::Modal::Client::ImageGetOrCreateRequest, ::Modal::Client::ImageGetOrCreateResponse
        rpc :ImageJoinStreaming, ::Modal::Client::ImageJoinStreamingRequest, stream(::Modal::Client::ImageJoinStreamingResponse)
        # Mounts
        rpc :MountGetOrCreate, ::Modal::Client::MountGetOrCreateRequest, ::Modal::Client::MountGetOrCreateResponse
        rpc :MountPutFile, ::Modal::Client::MountPutFileRequest, ::Modal::Client::MountPutFileResponse
        # Notebooks
        rpc :NotebookKernelPublishResults, ::Modal::Client::NotebookKernelPublishResultsRequest, ::Google::Protobuf::Empty
        # Proxies
        rpc :ProxyAddIp, ::Modal::Client::ProxyAddIpRequest, ::Modal::Client::ProxyAddIpResponse
        rpc :ProxyCreate, ::Modal::Client::ProxyCreateRequest, ::Modal::Client::ProxyCreateResponse
        rpc :ProxyDelete, ::Modal::Client::ProxyDeleteRequest, ::Google::Protobuf::Empty
        rpc :ProxyGet, ::Modal::Client::ProxyGetRequest, ::Modal::Client::ProxyGetResponse
        rpc :ProxyGetOrCreate, ::Modal::Client::ProxyGetOrCreateRequest, ::Modal::Client::ProxyGetOrCreateResponse
        rpc :ProxyList, ::Google::Protobuf::Empty, ::Modal::Client::ProxyListResponse
        rpc :ProxyRemoveIp, ::Modal::Client::ProxyRemoveIpRequest, ::Google::Protobuf::Empty
        # Queues
        rpc :QueueClear, ::Modal::Client::QueueClearRequest, ::Google::Protobuf::Empty
        rpc :QueueDelete, ::Modal::Client::QueueDeleteRequest, ::Google::Protobuf::Empty
        rpc :QueueGet, ::Modal::Client::QueueGetRequest, ::Modal::Client::QueueGetResponse
        rpc :QueueGetOrCreate, ::Modal::Client::QueueGetOrCreateRequest, ::Modal::Client::QueueGetOrCreateResponse
        rpc :QueueHeartbeat, ::Modal::Client::QueueHeartbeatRequest, ::Google::Protobuf::Empty
        rpc :QueueLen, ::Modal::Client::QueueLenRequest, ::Modal::Client::QueueLenResponse
        rpc :QueueList, ::Modal::Client::QueueListRequest, ::Modal::Client::QueueListResponse
        rpc :QueueNextItems, ::Modal::Client::QueueNextItemsRequest, ::Modal::Client::QueueNextItemsResponse
        rpc :QueuePut, ::Modal::Client::QueuePutRequest, ::Google::Protobuf::Empty
        # Sandboxes
        rpc :SandboxCreate, ::Modal::Client::SandboxCreateRequest, ::Modal::Client::SandboxCreateResponse
        rpc :SandboxGetLogs, ::Modal::Client::SandboxGetLogsRequest, stream(::Modal::Client::TaskLogsBatch)
        rpc :SandboxGetResourceUsage, ::Modal::Client::SandboxGetResourceUsageRequest, ::Modal::Client::SandboxGetResourceUsageResponse
        rpc :SandboxGetTaskId, ::Modal::Client::SandboxGetTaskIdRequest, ::Modal::Client::SandboxGetTaskIdResponse
        # needed for modal container exec
        rpc :SandboxGetTunnels, ::Modal::Client::SandboxGetTunnelsRequest, ::Modal::Client::SandboxGetTunnelsResponse
        rpc :SandboxList, ::Modal::Client::SandboxListRequest, ::Modal::Client::SandboxListResponse
        rpc :SandboxRestore, ::Modal::Client::SandboxRestoreRequest, ::Modal::Client::SandboxRestoreResponse
        rpc :SandboxSnapshot, ::Modal::Client::SandboxSnapshotRequest, ::Modal::Client::SandboxSnapshotResponse
        rpc :SandboxSnapshotFs, ::Modal::Client::SandboxSnapshotFsRequest, ::Modal::Client::SandboxSnapshotFsResponse
        rpc :SandboxSnapshotGet, ::Modal::Client::SandboxSnapshotGetRequest, ::Modal::Client::SandboxSnapshotGetResponse
        rpc :SandboxSnapshotWait, ::Modal::Client::SandboxSnapshotWaitRequest, ::Modal::Client::SandboxSnapshotWaitResponse
        rpc :SandboxStdinWrite, ::Modal::Client::SandboxStdinWriteRequest, ::Modal::Client::SandboxStdinWriteResponse
        rpc :SandboxTagsSet, ::Modal::Client::SandboxTagsSetRequest, ::Google::Protobuf::Empty
        rpc :SandboxTerminate, ::Modal::Client::SandboxTerminateRequest, ::Modal::Client::SandboxTerminateResponse
        rpc :SandboxWait, ::Modal::Client::SandboxWaitRequest, ::Modal::Client::SandboxWaitResponse
        # Secrets
        rpc :SecretDelete, ::Modal::Client::SecretDeleteRequest, ::Google::Protobuf::Empty
        rpc :SecretGetOrCreate, ::Modal::Client::SecretGetOrCreateRequest, ::Modal::Client::SecretGetOrCreateResponse
        rpc :SecretList, ::Modal::Client::SecretListRequest, ::Modal::Client::SecretListResponse
        # SharedVolumes
        rpc :SharedVolumeDelete, ::Modal::Client::SharedVolumeDeleteRequest, ::Google::Protobuf::Empty
        rpc :SharedVolumeGetFile, ::Modal::Client::SharedVolumeGetFileRequest, ::Modal::Client::SharedVolumeGetFileResponse
        rpc :SharedVolumeGetOrCreate, ::Modal::Client::SharedVolumeGetOrCreateRequest, ::Modal::Client::SharedVolumeGetOrCreateResponse
        rpc :SharedVolumeHeartbeat, ::Modal::Client::SharedVolumeHeartbeatRequest, ::Google::Protobuf::Empty
        rpc :SharedVolumeList, ::Modal::Client::SharedVolumeListRequest, ::Modal::Client::SharedVolumeListResponse
        rpc :SharedVolumeListFiles, ::Modal::Client::SharedVolumeListFilesRequest, ::Modal::Client::SharedVolumeListFilesResponse
        rpc :SharedVolumeListFilesStream, ::Modal::Client::SharedVolumeListFilesRequest, stream(::Modal::Client::SharedVolumeListFilesResponse)
        rpc :SharedVolumePutFile, ::Modal::Client::SharedVolumePutFileRequest, ::Modal::Client::SharedVolumePutFileResponse
        rpc :SharedVolumeRemoveFile, ::Modal::Client::SharedVolumeRemoveFileRequest, ::Google::Protobuf::Empty
        # Tasks
        rpc :TaskClusterHello, ::Modal::Client::TaskClusterHelloRequest, ::Modal::Client::TaskClusterHelloResponse
        rpc :TaskCurrentInputs, ::Google::Protobuf::Empty, ::Modal::Client::TaskCurrentInputsResponse
        rpc :TaskList, ::Modal::Client::TaskListRequest, ::Modal::Client::TaskListResponse
        rpc :TaskResult, ::Modal::Client::TaskResultRequest, ::Google::Protobuf::Empty
        # Tokens (web auth flow)
        rpc :TokenFlowCreate, ::Modal::Client::TokenFlowCreateRequest, ::Modal::Client::TokenFlowCreateResponse
        rpc :TokenFlowWait, ::Modal::Client::TokenFlowWaitRequest, ::Modal::Client::TokenFlowWaitResponse
        # Tunnels
        rpc :TunnelStart, ::Modal::Client::TunnelStartRequest, ::Modal::Client::TunnelStartResponse
        rpc :TunnelStop, ::Modal::Client::TunnelStopRequest, ::Modal::Client::TunnelStopResponse
        # Volumes
        rpc :VolumeCommit, ::Modal::Client::VolumeCommitRequest, ::Modal::Client::VolumeCommitResponse
        rpc :VolumeCopyFiles, ::Modal::Client::VolumeCopyFilesRequest, ::Google::Protobuf::Empty
        rpc :VolumeCopyFiles2, ::Modal::Client::VolumeCopyFiles2Request, ::Google::Protobuf::Empty
        rpc :VolumeDelete, ::Modal::Client::VolumeDeleteRequest, ::Google::Protobuf::Empty
        rpc :VolumeGetFile, ::Modal::Client::VolumeGetFileRequest, ::Modal::Client::VolumeGetFileResponse
        rpc :VolumeGetFile2, ::Modal::Client::VolumeGetFile2Request, ::Modal::Client::VolumeGetFile2Response
        rpc :VolumeGetOrCreate, ::Modal::Client::VolumeGetOrCreateRequest, ::Modal::Client::VolumeGetOrCreateResponse
        rpc :VolumeHeartbeat, ::Modal::Client::VolumeHeartbeatRequest, ::Google::Protobuf::Empty
        rpc :VolumeList, ::Modal::Client::VolumeListRequest, ::Modal::Client::VolumeListResponse
        rpc :VolumeListFiles, ::Modal::Client::VolumeListFilesRequest, stream(::Modal::Client::VolumeListFilesResponse)
        rpc :VolumeListFiles2, ::Modal::Client::VolumeListFiles2Request, stream(::Modal::Client::VolumeListFiles2Response)
        rpc :VolumePutFiles, ::Modal::Client::VolumePutFilesRequest, ::Google::Protobuf::Empty
        rpc :VolumePutFiles2, ::Modal::Client::VolumePutFiles2Request, ::Modal::Client::VolumePutFiles2Response
        rpc :VolumeReload, ::Modal::Client::VolumeReloadRequest, ::Google::Protobuf::Empty
        rpc :VolumeRemoveFile, ::Modal::Client::VolumeRemoveFileRequest, ::Google::Protobuf::Empty
        rpc :VolumeRemoveFile2, ::Modal::Client::VolumeRemoveFile2Request, ::Google::Protobuf::Empty
        rpc :VolumeRename, ::Modal::Client::VolumeRenameRequest, ::Google::Protobuf::Empty
        # Workspaces
        rpc :WorkspaceNameLookup, ::Google::Protobuf::Empty, ::Modal::Client::WorkspaceNameLookupResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
