name: Publish Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC for trusted provider: https://docs.npmjs.com/trusted-publishers#github-actions-configuration
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.event.head_commit.message, '[RELEASE] Prepare release for') || startsWith(github.event.head_commit.message, '[DEV-RELEASE] Prepare dev release for')
    environment: publish

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: true

    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "20.x"
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        cache-dependency-path: modal-js/package-lock.json

    - name: Ensure npm 11.5.1 or later for trusted publishing
      run: npm install -g npm@>=11.5.1

    - name: Install npm packages
      run: npm install
      working-directory: ./modal-js

    - name: Config git user
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Publish and push tags
      run: |
        if [[ "${{ github.event.head_commit.message }}" == "[DEV-RELEASE]"* ]]; then
          python ci/release.py publish --dev
        else
          python ci/release.py publish
        fi
